from enum import Enum, auto

class CivilizationOriginEvent(Enum):
    PROPHETIC_DEATH = auto()
    GREAT_WAR = auto()
    NATURAL_CATASTROPHE = auto()
    CELESTIAL_EVENT = auto()
    MIGRATION = auto()
    TECHNOLOGICAL_DISCOVERY = auto()
    DIVINE_REVELATION = auto()
    HEROIC_SACRIFICE = auto()
    FOUNDING_MYTH = auto()
    REBELLION = auto()
    UNIFICATION = auto()
    ECONOMIC_BOOM = auto()
    PLAGUE_OR_DISEASE = auto()
    MYSTICAL_ENCOUNTER = auto()
    CELESTIAL_GUIDANCE = auto()
    FIRST_CONTACT = auto()
    AI_UPRISING = auto()
    COLONY_SHIP_ARRIVAL = auto()
    TIME_TRAVEL_EVENT = auto()
    DIMENSIONAL_BREACH = auto()
    QUANTUM_LEAP = auto()
    STAR_FORGE_ACTIVATION = auto()
    PLANETARY_EXODUS = auto()