from enum import Enum, auto

class ModernCivilisationProfession(Enum):
    FARMER = auto()
    WORKER = auto()
    ARTISAN = auto()
    MERCHANT = auto()
    PRIEST = auto()
    SOLDIER = auto()
    SCHOLAR = auto()
    RULER = auto()
    DIPLOMAT = auto()
    ENGINEER = auto()
    HEALER = auto()
    SCIENTIST = auto()
    PHILOSOPHER = auto()
    SAILOR = auto()
    HUNTER = auto()
    NOMAD = auto()
    ENTERTAINER = auto()
    BUILDER = auto()
    LAW_KEEPER = auto()
    CRIMINAL = auto()
    SPY = auto()
    BANKER = auto()
    POLITICIAN = auto()
    TEACHER = auto()
    WRITER = auto()
    MINER = auto()
    TECHNICIAN = auto()
    PROGRAMMER = auto()
    ARTIST = auto()
    CLERIC = auto()
    CORPORATE_EXECUTIVE = auto()
    AI_HANDLER = auto()
    SPACE_PILOT = auto()