from enum import Enum, auto

class SocialStructure(Enum):
    TRIBAL = auto()
    FEUDAL = auto()
    CASTE_SYSTEM = auto()
    CLAN_BASED = auto()
    IMPERIAL_HIERARCHY = auto()
    THEOCRACY = auto()
    MERITOCRACY = auto()
    DEMOCRACY = auto()
    OLIGARCHY = auto()
    AUTOCRACY = auto()
    TECHNOCRACY = auto()
    ANARCHY = auto()
    CORPORATOCRACY = auto()
    MILITARY_JUNTA = auto()
    COMMUNAL = auto()
    SOCIALIST = auto()
    CAPITALIST = auto()
    UTOPIAN_COLLECTIVE = auto()
    AI_GOVERNANCE = auto()
    HIVE_MIND = auto()